import { Html, Head, Main, NextScript } from 'next/document'
import Favicon from '../components/Favicon';

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <meta name="Yoslie Portofolio" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charSet="utf-8" />
        <Favicon/>
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
